In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv("C:/Users/Asus/Downloads/spam_ham_dataset.csv")

data.head()

X label                                               text  label_num
0   605   ham  Subject: enron methanol ; meter # : 988291\r\n...          0
1  2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0
2  3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0
3  4685  spam  Subject: photoshop , windows , office . cheap ...          1
4  2030   ham  Subject: re : indian springs\r\nthis deal is t...          0

In [2]:
del(data['text'])

In [12]:
#variabel independen
x = data.drop(["label"], axis=1)
x.head()

#variabel dependen
y = data["label"]
y.head

<bound method NDFrame.head of 0        ham
1        ham
2        ham
3       spam
4        ham
        ... 
5166     ham
5167     ham
5168     ham
5169     ham
5170    spam
Name: label, Length: 5171, dtype: object>

In [13]:
#analisis menggunkan klasifikasi naive bayes
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state=123)

In [14]:
#Training set dan test set

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#memanggil fungsi klasifikasi Naive Bayes
model = GaussianNB()

#memasukkan data training pada fungsi klasifikasi naive bayes
train = model.fit(x_train, y_train)
train.class_count_

array([2925., 1211.])

In [15]:
#Menentukan hasil prediksi dari x_test
y_pred = train.predict(x_test)
y_pred

array(['ham', 'ham', 'spam', ..., 'ham', 'spam', 'spam'], dtype='<U4')

In [17]:
#Menentukan nilai probabilitas dari x_test
train.predict_proba(x_test)

array([[1.00000000e+000, 2.95854270e-105],
       [1.00000000e+000, 1.24143457e-106],
       [4.19512374e-099, 1.00000000e+000],
       ...,
       [1.00000000e+000, 1.28068705e-120],
       [1.80841766e-099, 1.00000000e+000],
       [5.65129393e-099, 1.00000000e+000]])

In [18]:
#Melakukan Cunfussion Matrix

#Import confusion_matrix model
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[747,   0],
       [  0, 288]], dtype=int64)

In [19]:
np.array(y_test)

array(['ham', 'ham', 'spam', ..., 'ham', 'spam', 'spam'], dtype=object)

In [21]:
#Menentukan nilai akurasi dari klasifikasi naive bayes
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       1.00      1.00      1.00       747
        spam       1.00      1.00      1.00       288

    accuracy                           1.00      1035
   macro avg       1.00      1.00      1.00      1035
weighted avg       1.00      1.00      1.00      1035

